### ISSUE TITLE
Crash using the camera

### ISSUE THREAD

**Issue by gabivitcord** [Werb/PickPhotoSample#30]
It happens on a SAMSUNG SM-G930F when the camera is the source to get the image and just after tap 'OK' on preview. Moreover, preview quality is quite slow.

`
08-10 12:07:16.983 20160-20160/com.vitcord.android.vitcord.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.vitcord.android.vitcord.debug, PID: 20160
                                                                                   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=39241, result=-1, data=Intent { act=inline-data flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.vitcord.android.vitcord.debug/com.werb.pickphotoview.PickPhotoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4481)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
                                                                                       at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                                       at com.werb.pickphotoview.PickPhotoActivity.onActivityResult(PickPhotoActivity.java:181)
                                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524) 
                                                                                       at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
`

**Comment by gergirod** [comment]
Any news about this one, I'm facing the same issue on google pixel

**Comment by rayliverified** [comment]
Sorry for not responding sooner. The photo capture mechanism follows the Android documentation. Have you included the provider in your manifest? Without the provider, the app will be unable to pass the result back. Hope this helps! 

```
<provider
        android:name="com.werb.pickphotoview.provider.PickProvider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/pick_file_paths"/>
    </provider>
```

**Comment by gabivitcord** [comment]
I got it... :-) Thank you so much, @searchy2.
