### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by Redman1037** [Werb/PickPhotoSample#35]
10-23 19:06:13.067 8321-8321/com.example.manohar.imagepickersampleapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.example.manohar.imagepickersampleapp, PID: 8321
                                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                                                                                            at com.werb.pickphotoview.PickPhotoView$Builder.<init>(PickPhotoView.kt)
                                                                                            at com.example.manohar.imagepickersampleapp.MainActivity$1.onClick(MainActivity.java:51)
                                                                                            at android.view.View.performClick(View.java:5201)
                                                                                            at android.view.View$PerformClick.run(View.java:21163)
                                                                                            at android.os.Handler.handleCallback(Handler.java:746)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.example.manohar.imagepickersampleapp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.manohar.imagepickersampleapp-2/lib/arm, /vendor/lib, /system/lib]]
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                            at com.werb.pickphotoview.PickPhotoView$Builder.<init>(PickPhotoView.kt) 
                                                                                            at com.example.manohar.imagepickersampleapp.MainActivity$1.onClick(MainActivity.java:51) 
                                                                                            at android.view.View.performClick(View.java:5201) 
                                                                                            at android.view.View$PerformClick.run(View.java:21163) 
                                                                                            at android.os.Handler.handleCallback(Handler.java:746) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                                        	Suppressed: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
                                                                                            at java.lang.Class.classForName(Native Method)
                                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                            		... 12 more
                                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Also PickConfig.PICK_PHOTO_DATA    and  PickConfig.INTENT_IMG_LIST_SELECT    are private , make them public**

**Comment by werbhelius** [comment]
Got!

**Comment by werbhelius** [comment]
bug fixed and published new version [0.3.6](https://github.com/Werb/PickPhotoSample/releases/tag/v0.3.6)

because new version build with Koltin . so sorry to cause this error.
new version will config some command in you'r module `build.gradle`, please see this [info](https://github.com/Werb/PickPhotoSample#gradle)

and if u don't want to use Kotlin , you can Dependency with old version like [0.3.0](https://github.com/Werb/PickPhotoSample/releases/tag/v0.3.0)
