### ISSUE TITLE
error

### ISSUE THREAD

**Issue by snsh22** [Werb/PickPhotoSample#40]
java.lang.RuntimeException: Unable to start activity ComponentInfo{comm.comquas.carsurvey/com.werb.pickphotoview.PickPhotoActivity}: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:163)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6326)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
                                                                         Caused by: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
                                                                            at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
                                                                            at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
                                                                            at android.content.res.Resources.getColor(Resources.java:966)
                                                                            at android.content.res.Resources.getColor(Resources.java:942)
                                                                            at com.werb.pickphotoview.extensions.ContextExtensionsKt.color(ContextExtensions.kt:11)
                                                                            at com.werb.pickphotoview.PickPhotoActivity.initToolbar(PickPhotoActivity.kt:56)
                                                                            at com.werb.pickphotoview.PickPhotoActivity.onCreate(PickPhotoActivity.kt:41)
                                                                            at android.app.Activity.performCreate(Activity.java:6847)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:163) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6326) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by werbhelius** [comment]
color value invalid
